"""Hierarchical MTF Trade Retention Diagnostics and Safeguards.

Tracks multi-stage veto funnel metrics (HWC veto rate, MWC incremental veto rate,
final trade retention ratio) and enforces retention floors (>= 50%) with low-sample
statistical guardrails (MIN_RETENTION_SAMPLE < 15 -> INSUFFICIENT_SUPPORT).
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import logging
from typing import Any, Mapping, Sequence, Union
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Standard guardrail constants
MIN_RETENTION_SAMPLE: int = 15
DEFAULT_RETENTION_FLOOR: float = 0.50
DEFAULT_RETENTION_TARGET: float = 0.60


@dataclass(frozen=True)
class TradeRetentionDiagnostics:
    """Dataclass holding trade retention funnel metrics and status.

    Attributes:
        raw_triggers: Total raw candidate entry triggers generated by LWC.
        hwc_vetoed: Number of candidate triggers filtered by HWC opposing macro bias.
        hwc_survived: Number of candidate triggers surviving HWC filter.
        mwc_vetoed: Number of HWC-surviving candidates filtered by MWC opposing setup.
        accepted_trades: Final count of accepted MTF entry signals.
        hwc_veto_rate: Proportion of raw triggers vetoed by HWC (hwc_vetoed / raw_triggers).
        mwc_incremental_veto_rate: Proportion of HWC survivors vetoed by MWC (mwc_vetoed / hwc_survived).
        mwc_absolute_veto_rate: Proportion of raw triggers vetoed by MWC (mwc_vetoed / raw_triggers).
        retention_ratio: Final trade retention ratio (accepted_trades / raw_triggers).
        retention_floor: Configured hard retention floor threshold.
        retention_target: Configured target retention ratio.
        min_retention_sample: Minimum sample threshold for hard floor validation.
        has_sufficient_support: Boolean indicating whether sample size >= min_retention_sample.
        passes_floor: Boolean indicating whether retention satisfies floor or sample is small.
        status: Informative status string ("PASS", "TARGET_MET", "PASS_BELOW_TARGET",
                "FAIL_RETENTION_FLOOR", or "INSUFFICIENT_SUPPORT").
    """

    raw_triggers: int
    hwc_vetoed: int
    hwc_survived: int
    mwc_vetoed: int
    accepted_trades: int
    hwc_veto_rate: float
    mwc_incremental_veto_rate: float
    mwc_absolute_veto_rate: float
    retention_ratio: float
    retention_floor: float
    retention_target: float
    min_retention_sample: int
    has_sufficient_support: bool
    passes_floor: bool
    status: str

    def to_dict(self) -> dict[str, Any]:
        """Convert dataclass fields to standard dictionary."""
        return asdict(self)


def compute_trade_retention_diagnostics(
    stats_or_raw: Union[Mapping[str, Any], int],
    hwc_vetoed: int | None = None,
    mwc_vetoed: int | None = None,
    accepted_trades: int | None = None,
    *,
    retention_floor: float = DEFAULT_RETENTION_FLOOR,
    retention_target: float = DEFAULT_RETENTION_TARGET,
    min_retention_sample: int = MIN_RETENTION_SAMPLE,
) -> dict[str, Any]:
    """Compute staged veto rates and evaluate retention floor guardrails.

    Formulas:
        HWC Veto Rate = HWC vetoed triggers / Raw LWC triggers
        MWC Incremental Veto Rate = MWC vetoed candidates / Candidates surviving HWC
        Final Trade Retention Ratio = Accepted MTF Trades / Raw LWC triggers

    Parameters
    ----------
    stats_or_raw : Mapping[str, Any] or int
        Dictionary returned by ``compose_hierarchical_signals`` or raw trigger count.
    hwc_vetoed : int or None, optional
        Count of triggers vetoed by HWC (used if stats_or_raw is int).
    mwc_vetoed : int or None, optional
        Count of triggers vetoed by MWC (used if stats_or_raw is int).
    accepted_trades : int or None, optional
        Count of accepted MTF trades (used if stats_or_raw is int).
    retention_floor : float, default 0.50
        Hard minimum retention ratio (e.g. 0.50 for 50%).
    retention_target : float, default 0.60
        Target retention ratio (e.g. 0.60 for 60%).
    min_retention_sample : int, default 15
        Minimum sample size required for hard floor enforcement.

    Returns
    -------
    dict[str, Any]
        Dictionary with all staged metrics, rates, and guardrail status.
    """
    if isinstance(stats_or_raw, Mapping):
        raw = int(stats_or_raw.get("raw_triggers", 0))
        n_hwc_veto = int(stats_or_raw.get("hwc_vetoed", 0))
        n_hwc_surv = int(stats_or_raw.get("hwc_survived", max(0, raw - n_hwc_veto)))
        n_mwc_veto = int(stats_or_raw.get("mwc_vetoed", 0))
        n_accepted = int(stats_or_raw.get("accepted_trades", max(0, n_hwc_surv - n_mwc_veto)))
    else:
        raw = int(stats_or_raw)
        n_hwc_veto = int(0 if hwc_vetoed is None else hwc_vetoed)
        n_hwc_surv = max(0, raw - n_hwc_veto)
        n_mwc_veto = int(0 if mwc_vetoed is None else mwc_vetoed)
        n_accepted = (
            int(accepted_trades)
            if accepted_trades is not None
            else max(0, n_hwc_surv - n_mwc_veto)
        )

    # Calculate staged rates safely
    hwc_veto_rate = float(n_hwc_veto / raw) if raw > 0 else 0.0
    mwc_incremental_veto_rate = float(n_mwc_veto / n_hwc_surv) if n_hwc_surv > 0 else 0.0
    mwc_absolute_veto_rate = float(n_mwc_veto / raw) if raw > 0 else 0.0
    retention_ratio = float(n_accepted / raw) if raw > 0 else 0.0

    # Evaluate guardrails
    has_sufficient_support = raw >= min_retention_sample

    if not has_sufficient_support:
        status = "INSUFFICIENT_SUPPORT"
        passes_floor = True  # Do not fail hard due to small sample size
    elif retention_ratio < retention_floor:
        status = "FAIL_RETENTION_FLOOR"
        passes_floor = False
    elif retention_ratio < retention_target:
        status = "PASS_BELOW_TARGET"
        passes_floor = True
    else:
        status = "PASS"
        passes_floor = True

    diagnostics = TradeRetentionDiagnostics(
        raw_triggers=raw,
        hwc_vetoed=n_hwc_veto,
        hwc_survived=n_hwc_surv,
        mwc_vetoed=n_mwc_veto,
        accepted_trades=n_accepted,
        hwc_veto_rate=hwc_veto_rate,
        mwc_incremental_veto_rate=mwc_incremental_veto_rate,
        mwc_absolute_veto_rate=mwc_absolute_veto_rate,
        retention_ratio=retention_ratio,
        retention_floor=float(retention_floor),
        retention_target=float(retention_target),
        min_retention_sample=int(min_retention_sample),
        has_sufficient_support=has_sufficient_support,
        passes_floor=passes_floor,
        status=status,
    )

    return diagnostics.to_dict()


def compute_granular_retention_diagnostics(
    df: pd.DataFrame,
    trigger_col: str = "lwc_trigger",
    hwc_veto_col: str = "hwc_veto",
    mwc_veto_col: str = "mwc_veto",
    accepted_col: str = "accepted",
    datetime_col: str = "datetime",
    symbol_col: str = "symbol",
    direction_col: str = "direction",
    fold_col: str = "fold_id",
    retention_floor: float = DEFAULT_RETENTION_FLOOR,
    retention_target: float = DEFAULT_RETENTION_TARGET,
    min_retention_sample: int = MIN_RETENTION_SAMPLE,
) -> dict[str, Any]:
    """Compute trade retention funnel metrics partitioned along multiple dimensions.

    Partitions metrics:
      - Overall
      - By Direction ('long', 'short')
      - By Symbol (e.g. 'BTCUSDT', 'ETHUSDT')
      - By Fold (e.g. 1, 2, 3, 4)
      - By Month (e.g. '2024-01', '2024-02')

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing trigger and veto outcome columns.
    trigger_col : str, default "lwc_trigger"
        Column indicating raw LWC triggers (boolean or non-zero numeric).
    hwc_veto_col : str, default "hwc_veto"
        Column indicating HWC veto flag (boolean or 1/0).
    mwc_veto_col : str, default "mwc_veto"
        Column indicating MWC veto flag (boolean or 1/0).
    accepted_col : str, default "accepted"
        Column indicating accepted MTF trade flag (boolean or 1/0).
    datetime_col : str, default "datetime"
        Datetime column for monthly partitioning.
    symbol_col : str, default "symbol"
        Symbol column for per-asset partitioning.
    direction_col : str, default "direction"
        Direction column for per-direction partitioning.
    fold_col : str, default "fold_id"
        Fold ID column for per-fold partitioning.
    retention_floor : float, default 0.50
        Hard retention floor.
    retention_target : float, default 0.60
        Target retention ratio.
    min_retention_sample : int, default 15
        Low-sample guard threshold.

    Returns
    -------
    dict[str, Any]
        Dictionary organized with sub-dictionaries for overall and each partition.
    """
    if df.empty:
        empty_diag = compute_trade_retention_diagnostics(
            0,
            retention_floor=retention_floor,
            retention_target=retention_target,
            min_retention_sample=min_retention_sample,
        )
        return {
            "overall": empty_diag,
            "by_direction": {},
            "by_symbol": {},
            "by_fold": {},
            "by_month": {},
        }

    def _calc_subset_diag(subset: pd.DataFrame) -> dict[str, Any]:
        if subset.empty or trigger_col not in subset.columns:
            return compute_trade_retention_diagnostics(
                0,
                retention_floor=retention_floor,
                retention_target=retention_target,
                min_retention_sample=min_retention_sample,
            )

        trig_mask = subset[trigger_col] != 0
        raw = int(trig_mask.sum())
        if raw == 0:
            return compute_trade_retention_diagnostics(
                0,
                retention_floor=retention_floor,
                retention_target=retention_target,
                min_retention_sample=min_retention_sample,
            )

        trig_df = subset.loc[trig_mask]
        n_hwc_veto = int((trig_df[hwc_veto_col] != 0).sum()) if hwc_veto_col in trig_df.columns else 0
        n_mwc_veto = int((trig_df[mwc_veto_col] != 0).sum()) if mwc_veto_col in trig_df.columns else 0
        if accepted_col in trig_df.columns:
            n_accepted = int((trig_df[accepted_col] != 0).sum())
        else:
            n_accepted = max(0, raw - n_hwc_veto - n_mwc_veto)

        stats = {
            "raw_triggers": raw,
            "hwc_vetoed": n_hwc_veto,
            "hwc_survived": max(0, raw - n_hwc_veto),
            "mwc_vetoed": n_mwc_veto,
            "accepted_trades": n_accepted,
        }
        return compute_trade_retention_diagnostics(
            stats,
            retention_floor=retention_floor,
            retention_target=retention_target,
            min_retention_sample=min_retention_sample,
        )

    # 1. Overall
    overall = _calc_subset_diag(df)

    # 2. By Direction
    by_direction: dict[str, Any] = {}
    if direction_col in df.columns:
        for val, group in df.groupby(direction_col, observed=True):
            by_direction[str(val)] = _calc_subset_diag(group)

    # 3. By Symbol
    by_symbol: dict[str, Any] = {}
    if symbol_col in df.columns:
        for val, group in df.groupby(symbol_col, observed=True):
            by_symbol[str(val)] = _calc_subset_diag(group)

    # 4. By Fold
    by_fold: dict[str, Any] = {}
    if fold_col in df.columns:
        for val, group in df.groupby(fold_col, observed=True):
            by_fold[str(val)] = _calc_subset_diag(group)

    # 5. By Month
    by_month: dict[str, Any] = {}
    if datetime_col in df.columns:
        dt = pd.to_datetime(df[datetime_col])
        month_keys = dt.dt.strftime("%Y-%m")
        for val, group in df.groupby(month_keys, observed=True):
            by_month[str(val)] = _calc_subset_diag(group)

    return {
        "overall": overall,
        "by_direction": by_direction,
        "by_symbol": by_symbol,
        "by_fold": by_fold,
        "by_month": by_month,
    }


def format_retention_report(diagnostics: dict[str, Any]) -> str:
    """Format granular retention diagnostics dictionary into a readable markdown report table."""
    lines: list[str] = [
        "# Trade Retention Funnel Diagnostics Report",
        "",
    ]

    overall = diagnostics.get("overall", diagnostics)
    lines.extend([
        "## Overall Funnel Summary",
        f"- **Raw LWC Triggers:** {overall.get('raw_triggers', 0)}",
        f"- **HWC Vetoed:** {overall.get('hwc_vetoed', 0)} ({overall.get('hwc_veto_rate', 0.0):.1%})",
        f"- **HWC Survived:** {overall.get('hwc_survived', 0)}",
        f"- **MWC Incremental Vetoed:** {overall.get('mwc_vetoed', 0)} ({overall.get('mwc_incremental_veto_rate', 0.0):.1%})",
        f"- **Accepted MTF Trades:** {overall.get('accepted_trades', 0)}",
        f"- **Final Retention Ratio:** {overall.get('retention_ratio', 0.0):.1%} (Floor: {overall.get('retention_floor', 0.5):.1%}, Target: {overall.get('retention_target', 0.6):.1%})",
        f"- **Status:** `{overall.get('status', 'UNKNOWN')}` (Passes Floor: {overall.get('passes_floor', False)})",
        "",
    ])

    for partition_name, key in [
        ("Direction Breakdown", "by_direction"),
        ("Symbol Breakdown", "by_symbol"),
        ("Fold Breakdown", "by_fold"),
        ("Monthly Breakdown", "by_month"),
    ]:
        part_dict = diagnostics.get(key, {})
        if part_dict:
            lines.append(f"## {partition_name}")
            lines.append("| Partition | Raw Triggers | HWC Veto | MWC Veto | Accepted | Retention | Status |")
            lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
            for sub_k, sub_v in part_dict.items():
                lines.append(
                    f"| {sub_k} | {sub_v.get('raw_triggers', 0)} | "
                    f"{sub_v.get('hwc_vetoed', 0)} ({sub_v.get('hwc_veto_rate', 0.0):.0%}) | "
                    f"{sub_v.get('mwc_vetoed', 0)} ({sub_v.get('mwc_incremental_veto_rate', 0.0):.0%}) | "
                    f"{sub_v.get('accepted_trades', 0)} | "
                    f"{sub_v.get('retention_ratio', 0.0):.1%} | "
                    f"`{sub_v.get('status', 'N/A')}` |"
                )
            lines.append("")

    return "\n".join(lines)
