
from __future__ import annotations

import os

_PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), os.pardir))

TRAIN_CSV_PATH = "data/train.csv"
TEST_CSV_PATH = "data/test.csv"
EVALUATOR_REFERENCE_SCHEMA_PATH = "data/train.csv"
EVALUATOR_EVALUATION_FILE_PATH = "data/test.csv"
TRAIN_75_PATH = "data/train_75.parquet"
VALIDATION_25_PATH = "data/validation_25.parquet"
OUTPUTS_DIR = "outputs"
RUN_LOG_PATH = os.path.join(OUTPUTS_DIR, "run.log")
REPORTS_DIR = "outputs/reports"
PHASE2_POOL_DIR = os.path.join(_PROJECT_ROOT, "pools")
PHASE2_POOL_PATHS = {
    "long": os.path.join(PHASE2_POOL_DIR, "phase2_long_pool.json"),
    "short": os.path.join(PHASE2_POOL_DIR, "phase2_short_pool.json"),
}
PHASE2_HISTORY_PATHS = {
    "long": os.path.join(PHASE2_POOL_DIR, "phase2_long_history.json"),
    "short": os.path.join(PHASE2_POOL_DIR, "phase2_short_history.json"),
}
PHASE2_ARCHIVE_DIR = os.path.join(_PROJECT_ROOT, "phase2_rule_archive")
PHASE2_ARCHIVE_PATHS = {
    "long": os.path.join(PHASE2_ARCHIVE_DIR, "phase2_long_archive.json"),
    "short": os.path.join(PHASE2_ARCHIVE_DIR, "phase2_short_archive.json"),
}

LABEL_COLUMNS = [
    "label_open_next",
    "label_close_288",
    "label_min_288",
    "label_max_288",
    "label_max_before_min",
]
META_COLUMNS = ["datetime", "symbol"]
INTERNAL_COLUMNS = ("_symbol_bar_index",)
TAIL_DROP_ROWS = 0

INITIAL_CAPITAL = 1000.0
LEVERAGE = 1.0
FEE_PCT = 0.20
MAX_HOLD_CANDLES = 288
MAX_TOTAL_EXPOSURE_PCT = 100.0
MIN_POSITION_NOTIONAL = 1.0

PHASE2_TP = 2.0
PHASE2_SL = 1.0
PHASE2_CAPITAL_PCT = 48.0

MIN_CONDITIONS = 3
MAX_CONDITIONS = 5
MIN_TRADE_SUPPORT = 150
SUPPORT_PENALTY_MAX = 10.0
MIN_TRADE_POOL_FLOOR = 38

SORTINO_CAP = 10.0
PHASE2_POPULATION_SIZE = 120
PHASE2_GENERATIONS = 50
PHASE2_ARCHIVE_MAX_SIZE = 500
PHASE2_ARCHIVE_SEED_FRACTION = 0.35
PHASE2_ALGORITHM = "NSGA3"

PHASE3_MIN_RULES = 1
PHASE3_MAX_RULES = 5
PHASE3_MIN_SYMBOL_COVERAGE = 7
PHASE3_USE_GPU = False
PHASE3_REFINE_GENERATIONS = 0
PHASE3_REFINE_POP_SIZE = 0
PHASE3_GREEDY_WEIGHTS = (1.0, 0.7, 0.5)
PHASE3_SYMBOL_CONSISTENCY_WEIGHT = 10.0


CONDITION_SUPPORT_ENABLED = True
CONDITION_SUPPORT_WINDOW_DAYS = 30
CONDITION_SUPPORT_ULTRA_RARE_PCT = 0.0005
CONDITION_SUPPORT_RARE_PCT = 0.005
CONDITION_SUPPORT_BROAD_PCT = 0.20
CONDITION_SUPPORT_VERY_BROAD_PCT = 0.40
CONDITION_SUPPORT_DROP_ULTRA_RARE = True
CONDITION_SUPPORT_RARE_WEIGHT = 0.35
CONDITION_SUPPORT_BROAD_WEIGHT = 0.45
CONDITION_SUPPORT_VERY_BROAD_WEIGHT = 0.15
CONDITION_SUPPORT_MIN_STABILITY_WEIGHT = 0.20

PHASE2_MULTI_ARCHIVE_ENABLED = True
PHASE2_MULTI_ARCHIVE_PER_METRIC = 40
PHASE2_MULTI_ARCHIVE_METRICS = (
    "sortino_ratio",
    "total_return_pct",
    "max_drawdown_pct",
    "win_rate",
    "executed_trades",
)

PHASE3_HIDDEN_VALIDATION_ENABLED = True
PHASE3_HIDDEN_WINDOW_DAYS = 90
PHASE3_HIDDEN_STRIDE_DAYS = 30
PHASE3_HIDDEN_MAX_WINDOWS = 6
PHASE3_HIDDEN_MIN_ROWS = 10_000
PHASE3_HIDDEN_WORST_RETURN_FLOOR = -5.0
PHASE3_HIDDEN_WORST_RETURN_WEIGHT = 0.35
PHASE3_HIDDEN_SORTINO_WEIGHT = 0.20
PHASE3_HIDDEN_DRAWDOWN_WEIGHT = 0.05

AUTO_SEARCH_RUNS = 2
AUTO_SEARCH_START_DIRECTION = "long"
AUTO_SEARCH_OUTPUT_ROOT = os.path.join(OUTPUTS_DIR, "auto_search")


PHASE4_RL_ALGORITHM = "DDPG"
PHASE4_TP_MIN = 2.0
PHASE4_TP_MAX = 5.0
PHASE4_SL_MIN = 1.0
PHASE4_SL_MAX = 2.5
PHASE4_CAPITAL_PCT_MIN = 1.0
PHASE4_CAPITAL_PCT_MAX = 12.5
PHASE4_TOTAL_CAP_PENALTY = 2.0
PHASE4_RL_EVAL_WINDOW = 288
PHASE4_VAL_SORTINO_WEIGHT = 0.2
PHASE4_VAL_SORTINO_BONUS_CAP = 5.0
PHASE4_TOTAL_TIMESTEPS = 500_000
PHASE4_ELBOW_WINDOW = 15

LOG_GENERATION_INTERVAL = 0

PHASE1_DISPERSION_THRESHOLD = 0.95
PHASE1_TOP_K_FEATURES = 25
PHASE1_MAX_FEATURE_OVERLAP = 0.50
PHASE1_SAMPLING_TOTAL = 150_000


PURGED_CV_ENABLED = True
PURGED_CV_N_SPLITS = 4
PURGED_CV_EMBARGO_CANDLES = MAX_HOLD_CANDLES
PURGED_CV_MIN_TRAIN_FRACTION = 0.45
PURGED_CV_MIN_VALID_ROWS = 5_000

PHASE1_SIGN_CONSISTENCY_ENABLED = True
PHASE1_SIGN_CONSISTENCY_FOLDS = 4
PHASE1_SIGN_CONSISTENCY_WEIGHT = 0.35
PHASE1_SIGN_CONSISTENCY_MIN_ABS_CORR = 1e-5

PHASE2_THREE_STRATA_ENABLED = True
PHASE2_STRATA_ELITE_FRAC = 0.40
PHASE2_STRATA_EXPLORER_FRAC = 0.35
PHASE2_STRATA_REGIME_FRAC = 0.25
PHASE2_FEATURE_SOFTMAX_TEMPERATURE = 0.35
PHASE2_REGIME_FEATURE_KEYWORDS = (
    "vol", "atr", "bb_width", "compression", "range", "trend", "regime",
    "breakout", "drawdown", "channel", "adx", "dmi", "semivol",
)
PHASE2_FALLBACK_ENABLED = True
PHASE2_FALLBACK_MIN_POOL_SIZE = 40
PHASE2_FALLBACK_MAX_RULES = 200
PHASE2_CV_FILTER_ENABLED = True
PHASE2_CV_MAX_RULES_TO_EVALUATE = 350
PHASE2_CV_MIN_WORST_RETURN = -8.0
PHASE2_CV_MIN_WORST_PF = 0.80
PHASE2_CV_MAX_WORST_DD = 18.0
PHASE2_CV_MIN_FOLD_TRADES = 10

PHASE3_PURGED_CV_ENABLED = True
PHASE3_CV_PENALTY_WEIGHT = 1.0
PHASE3_WORST_RETURN_FLOOR = -2.0
PHASE3_WORST_PF_FLOOR = 1.00
PHASE3_WORST_DD_CEIL = 12.0
PHASE3_MIN_FOLD_TRADES = 20
PHASE3_SIGNAL_OVERLAP_ENABLED = True
PHASE3_MAX_PAIR_OVERLAP = 0.35
PHASE3_OVERLAP_WEIGHT = 18.0
PHASE3_GAP_RETURN_WEIGHT = 0.45
PHASE3_GAP_PF_WEIGHT = 3.00
PHASE3_GAP_DD_WEIGHT = 0.15
PHASE3_PER_SYMBOL_SURVIVAL_ENABLED = True
PHASE3_MIN_PROFITABLE_SYMBOLS = 6
PHASE3_MAX_SINGLE_SYMBOL_PNL_SHARE = 0.45
PHASE3_PER_SYMBOL_WEIGHT = 8.0

PHASE4_OPTIMIZER = "robust_grid"
PHASE4_TP_GRID = (1.5, 2.0, 2.5, 3.0, 3.5, 4.0)
PHASE4_SL_GRID = (0.8, 1.0, 1.2, 1.5, 2.0)
PHASE4_CAPITAL_GRID = (1.0, 2.0, 3.0, 5.0, 7.5, 10.0, 12.5)
PHASE4_ROBUST_MAX_TRIALS = 180
PHASE4_ROBUST_MIN_WORST_PF = 0.65
PHASE4_ROBUST_MAX_WORST_DD = 25.0
PHASE4_ROBUST_MIN_FOLD_TRADES = 5
PHASE4_ROBUST_EXPOSURE_WEIGHT = 0.002

AUTO_SEARCH_HOURS = 24.0
AUTO_SEARCH_RUN_FINAL_TEST = False
AUTO_SEARCH_SCORE_MIN_TRADES = 60

PHASE2_ROW_SAMPLE_TOTAL = PHASE1_SAMPLING_TOTAL

SYMBOL_SPECIALIZATION_ENABLED = True
SYMBOL_SPECIALIZATION_MAX_SYMBOLS_PER_RULE = 3
SYMBOL_SPECIALIZATION_MIN_TRADES = 20
SYMBOL_SPECIALIZATION_MIN_PF = 1.02
SYMBOL_SPECIALIZATION_MIN_SCORE = -2.0

MONTHLY_VALIDATION_ENABLED = True
MONTHLY_WINDOW_DAYS = 30
MONTHLY_WINDOW_STRIDE_DAYS = 30
MONTHLY_WINDOW_MIN_ROWS = 2500
MONTHLY_WINDOW_MAX_WINDOWS = 36
MONTHLY_RECENCY_WEIGHT = 2.2
MONTHLY_MIN_TRADES = 20
MONTHLY_MIN_PROFITABLE_RATIO = 0.60
MONTHLY_WORST_RETURN_FLOOR = -1.5
MONTHLY_WORST_PF_FLOOR = 0.85
MONTHLY_MAX_DD = 8.0
MONTHLY_WORST_RETURN_WEIGHT = 1.2
MONTHLY_WORST_PF_WEIGHT = 8.0
MONTHLY_DD_WEIGHT = 0.7
MONTHLY_PROFITABLE_RATIO_WEIGHT = 15.0
MONTHLY_TREND_WEIGHT = 2.0
MONTHLY_LATEST_WEIGHT = 0.6
PHASE3_MONTHLY_PENALTY_WEIGHT = 1.0
PHASE4_MONTHLY_SCORE_WEIGHT = 0.70


RULE_GENERATION_ENABLED = True
RULE_GEN_TOP_SEEDS = 40
RULE_GEN_EXPANSIONS_PER_SEED = 2
RULE_GEN_MIN_FEATURE_CONDITIONS = 5
RULE_GEN_MAX_FEATURE_CONDITIONS = 9
RULE_GEN_MAX_AND_PAIRS = 100
RULE_GEN_MAX_BACKTEST_CANDIDATES = 320
RULE_GEN_MAX_RAW_SIGNALS = 9000
RULE_REPAIR_MIN_FEATURE_CONDITIONS = 4
RULE_REPAIR_MAX_FEATURE_CONDITIONS = 9
RULE_REPAIR_MAX_PER_FAMILY = 2
TEMPLATE_GENERATOR_MAX_RULES = 80
APRIORI_MAX_CONDITION_BANK = 140
APRIORI_MAX_SEED_RULES = 100
APRIORI_MIN_SINGLE_SUPPORT = 0.002
APRIORI_MAX_SINGLE_SUPPORT = 0.35
APRIORI_MIN_PAIR_SUPPORT = 0.001
APRIORI_MIN_LIFT_LIKE = 1.05
PHASE3_SMART_POPULATION_ENABLED = True
PHASE3_RULE_CLUSTER_COUNT = 32

RETURN_DD_FLOOR = 1.0
PHASE3_GREEDY_EARLY_STOP = True
PHASE3_GREEDY_MIN_IMPROVEMENT = 0.0
PHASE4_MAX_TOTAL_CAPITAL = 35.0


RB_ENGINE_ENABLED = True
RB_DEFAULT_TP = 2.0
RB_DEFAULT_SL = 1.2
RB_DEFAULT_CAPITAL_PCT = 12.5
RB_MIN_TRAIN_RETURN = 0.0
RB_MIN_VALID_RETURN = 0.0
RB_MIN_TRAIN_PF = 1.00
RB_MIN_VALID_PF = 1.00
RB_MIN_TRAIN_TRADES = 20
RB_MIN_VALID_TRADES = 12
RB_RULESET_MIN_TRAIN_TRADES = 30
RB_RULESET_MIN_VALID_TRADES = 20
RB_MAX_POOL_RULES_TO_EVALUATE = 900
RB_KEEP_TOP_RULES = 140
RB_MAX_RULES = 5
RB_MAX_PAIR_OVERLAP = 0.24
RB_RULESET_MUST_BEAT_SUBSETS = True
RB_MIN_SCORE_IMPROVEMENT = 0.05
RB_MIN_TRAIN_RETURN_IMPROVEMENT = 0.01
RB_MIN_VALID_RETURN_IMPROVEMENT = 0.01
RB_RETURN_DD_FLOOR = 0.50
RB_TRADE_PENALTY = 0.70
RB_TRAIN_VALID_RATIO_GAP_WEIGHT = 6.0
RB_TRAIN_VALID_RETURN_GAP_WEIGHT = 0.25

RB_REQUIRE_TRAIN_SLIGHTLY_ABOVE_TEST = True
RB_TRAIN_VALID_MIN_RATIO = 1.03
RB_TRAIN_VALID_MAX_RATIO = 1.35
RB_TRAIN_VALID_MIN_ABS_GAP = 0.20
RB_TRAIN_VALID_MAX_ABS_GAP = 12.0
RB_TRAIN_BELOW_TEST_PENALTY = 900.0
RB_TRAIN_TOO_HIGH_PENALTY = 220.0
RB_TRAIN_VALID_SHAPE_BONUS = 160.0
RB_TP_GRID = (1.0, 1.2, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0)
RB_SL_GRID = (1.0, 1.2, 1.5, 2.0, 2.5, 3.0)
RB_CAPITAL_GRID = (5.0, 7.5, 10.0, 12.5, 15.0, 20.0, 25.0, 35.0, 50.0)
RB_MAX_TOTAL_CAPITAL = 95.0
RB_RISK_OPT_PASSES = 2
RB_RISK_MIN_IMPROVEMENT = 0.02

RB_EVALUATOR_ORDER_COMPAT = True
RB_USE_EVALUATOR_V5_SCORING = True
RB_REQUIRE_TP_SL_ABOVE_ONE = True
RB_MIN_TP = 1.0
RB_MIN_SL = 1.0
RB_MAX_SKIPPED_SIGNAL_RATIO = 0.20
RB_MIN_EXECUTED_RAW_RATIO = 0.60
RB_SKIPPED_RATIO_PENALTY = 3500.0
RB_EXECUTED_RATIO_PENALTY = 2500.0
RB_MAX_SIMULTANEOUS_POSITIONS = 10
RB_MAX_POSITIONS_PENALTY = 120.0

RB_RULE_ADD_BY_RETURN_ONLY = True
RB_RULE_ADD_IGNORE_OVERLAP = True
RB_RULE_ADD_IGNORE_SUBSET_BEAT = True
RB_MIN_COMBINED_RETURN_IMPROVEMENT = 0.05
RB_GLOBAL_BANK_ENABLED = True
RB_GLOBAL_COMPOSE_AFTER_EACH_RUN = True
RB_GLOBAL_BANK_DIRNAME = "rb_bank"
RB_GLOBAL_BANK_MAX_RULES_PER_DIRECTION = 700
RB_GLOBAL_BANK_IMPORT_TOP_SINGLE_RULES = 80
RB_GLOBAL_MAX_RULES = 12
RB_GLOBAL_MIN_COMBINED_RETURN_IMPROVEMENT = 0.05
RB_GLOBAL_REQUIRE_POSITIVE_TRAIN_VALID = True
RB_GLOBAL_RISK_OPT_PASSES = 2
RB_GLOBAL_BEST_DIRNAME = "best_global"
RB_GLOBAL_TP_GRID = (1.5, 2.0, 3.0, 5.0, 8.0)
RB_GLOBAL_SL_GRID = (1.2, 1.5, 2.0, 2.5)
RB_GLOBAL_CAPITAL_GRID = (5.0, 12.5, 25.0, 50.0)
RB_GLOBAL_MAX_TOTAL_CAPITAL = 100.0



RB_REQUIRE_SYMBOL_FILTERS = True
RB_SYMBOL_MAX_SYMBOLS_PER_RULE = 3
RB_SYMBOL_TOP_SINGLE_SYMBOLS = 5
RB_SYMBOL_MAX_VARIANTS_PER_RULE = 10
RB_SYMBOL_MIN_TRAIN_TRADES = 10
RB_SYMBOL_MIN_TEST_TRADES = 6
RB_SYMBOL_USE_COMBINATIONS = True
RB_SYMBOL_STRICT_OUTPUT_CHECK = True

RB_USE_EVALUATOR_V5_FILES = True
RB_USE_EVALUATOR_V5_FILES = True
