"""
Property-based tests for gpu_fuzzy_trader.phases.phase2_rule_pool.Rule_Pool_Generator

Property 19: Phase 2 Static Risk Parameters
  **Validates: Requirements 8.4**
  For any run of Rule_Pool_Generator, the backtest engine must always be
  called with tp=PHASE2_TP, sl=PHASE2_SL, capital_pct=PHASE2_CAPITAL_PCT.
  PHASE2_TP=4.0, PHASE2_SL=2.0, PHASE2_CAPITAL_PCT=50.0.

Property 20: Rule Condition Count Bounds
  **Validates: Requirements 8.6**
  For any pool generated by Rule_Pool_Generator, every rule in the pool
  must have active conditions in [MIN_CONDITIONS, MAX_CONDITIONS].
  MIN_CONDITIONS=2, MAX_CONDITIONS=5.
"""

from __future__ import annotations

import os
import tempfile

import numpy as np
import pandas as pd
import pytest
from hypothesis import given, HealthCheck
from hypothesis import strategies as st

from tests.property.hypothesis_config import prop_settings

from gpu_fuzzy_trader import config as _cfg
from gpu_fuzzy_trader.phases.phase2_rule_pool import (
    Rule_Pool_Generator,
    _count_active_conditions,
    _get_dont_cares,
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PHASE2_TP = _cfg.PHASE2_TP                  # 4.0
PHASE2_SL = _cfg.PHASE2_SL                  # 2.0
PHASE2_CAPITAL_PCT = _cfg.PHASE2_CAPITAL_PCT  # 50.0
MIN_CONDITIONS = _cfg.MIN_CONDITIONS          # 2
MAX_CONDITIONS = _cfg.MAX_CONDITIONS          # 5


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_feature_infos(modes: list[str]) -> list[dict]:
    """Create a minimal feature_infos list from a list of mode strings."""
    return [{"name": f"feat_{i}", "mode": m, "score": 0.5} for i, m in enumerate(modes)]


def _make_train_df(
    n_rows: int,
    n_features: int,
    symbols: list[str],
    seed: int = 42,
) -> pd.DataFrame:
    """
    Build a minimal training DataFrame with all required label columns and
    integer-valued feature columns (0–4, matching 'positive' mode).
    """
    rng = np.random.default_rng(seed)
    rows_per_sym = max(1, n_rows // len(symbols))
    dfs = []
    for sym in symbols:
        n = rows_per_sym
        open_next = rng.uniform(100.0, 200.0, size=n)
        max_288 = open_next * rng.uniform(0.98, 1.10, size=n)
        min_288 = open_next * rng.uniform(0.90, 1.02, size=n)
        close_288 = open_next * rng.uniform(0.95, 1.05, size=n)
        max_before_min = rng.integers(0, 2, size=n).astype(float)

        data: dict = {
            "datetime": pd.date_range("2024-01-01", periods=n, freq="5min"),
            "symbol": sym,
            "label_open_next": open_next,
            "label_close_288": close_288,
            "label_min_288": min_288,
            "label_max_288": max_288,
            "label_max_before_min": max_before_min,
            "_symbol_bar_index": np.arange(n),
        }
        for i in range(n_features):
            data[f"feat_{i}"] = rng.integers(0, 5, size=n).astype(float)

        dfs.append(pd.DataFrame(data))

    return pd.concat(dfs, ignore_index=True)


@pytest.fixture(autouse=True)
def _isolate_phase2_archive_paths(tmp_path):
    """Keep persistent Phase 2 archive files under the per-test temp directory."""
    import gpu_fuzzy_trader.phases.phase2_rule_pool as m

    original_archive = m._ARCHIVE_PATHS.copy()
    m._ARCHIVE_PATHS["long"] = os.path.join(
        tmp_path, "phase2_long_archive.json")
    m._ARCHIVE_PATHS["short"] = os.path.join(
        tmp_path, "phase2_short_archive.json")
    try:
        yield
    finally:
        m._ARCHIVE_PATHS.update(original_archive)


# ---------------------------------------------------------------------------
# Mock engine that records every simulate_rule_batch call
# ---------------------------------------------------------------------------

class _RecordingEngine:
    """
    Drop-in replacement for GPUBacktestEngine / CPUBacktestEngine.

    Records every call to simulate_rule_batch so tests can assert that
    the static Phase 2 risk parameters were used.
    """

    def __init__(self):
        self.calls: list[dict] = []

    def simulate_rule_batch(
        self,
        chromosomes: np.ndarray,
        tp: float,
        sl: float,
        capital_pct: float,
        **kwargs,
    ) -> list[dict]:
        self.calls.append({"tp": tp, "sl": sl, "capital_pct": capital_pct})
        # Return a plausible metrics dict for each chromosome in the batch
        return [
            {
                "sortino_ratio": 1.0,
                "total_return_pct": 1.0,
                "max_drawdown_pct": 0.5,
                "win_rate": 55.0,
                "executed_trades": 25,
            }
            for _ in range(len(chromosomes))
        ]


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Supported feature modes (must match encoder.get_dont_care)
_MODES = ["binary", "ternary", "positive",
          "sparse_positive", "sparse_signed", "signed"]


@st.composite
def feature_infos_and_train_df(draw: st.DrawFn):
    """
    Generate a (feature_infos, train_df) pair suitable for constructing a
    Rule_Pool_Generator with tiny pop/gen settings.

    Varies:
      - Number of features (2–6, so condition bounds are reachable)
      - Feature modes (any valid mode)
      - Number of symbols (1–3)
      - Number of rows per symbol (50–150)
    """
    n_features = draw(st.integers(min_value=2, max_value=6))
    modes = draw(
        st.lists(
            st.sampled_from(_MODES),
            min_size=n_features,
            max_size=n_features,
        )
    )
    n_symbols = draw(st.integers(min_value=1, max_value=3))
    rows_per_sym = draw(st.integers(min_value=50, max_value=150))
    seed = draw(st.integers(min_value=0, max_value=2**31 - 1))

    symbols = [f"SYM_{i}" for i in range(n_symbols)]
    n_rows = rows_per_sym * n_symbols

    feature_infos = _make_feature_infos(modes)
    train_df = _make_train_df(n_rows, n_features, symbols, seed=seed)

    return feature_infos, train_df


# ---------------------------------------------------------------------------
# Property 19: Phase 2 Static Risk Parameters
# Validates: Requirements 8.4
# ---------------------------------------------------------------------------

@given(args=feature_infos_and_train_df())
@prop_settings(
    max_examples=20,
    suppress_health_check=[HealthCheck.too_slow,
                           HealthCheck.function_scoped_fixture],
    deadline=None,
)
def test_property_19_phase2_static_risk_parameters(
    args: tuple[list[dict], pd.DataFrame],
) -> None:
    """
    **Property 19: Phase 2 Static Risk Parameters**
    **Validates: Requirements 8.4**

    For any run of Rule_Pool_Generator (with varying feature_infos and
    datasets), the backtest engine must always be called with:
      tp          = PHASE2_TP          (4.0)
      sl          = PHASE2_SL          (2.0)
      capital_pct = PHASE2_CAPITAL_PCT (50.0)

    We inject a recording mock engine to intercept every simulate_rule_batch
    call and assert the parameters are exactly the Phase 2 static values.
    """
    feature_infos, train_df = args

    with tempfile.TemporaryDirectory() as tmp_dir:
        # Redirect output files to a temp dir so we don't pollute real outputs/
        import gpu_fuzzy_trader.phases.phase2_rule_pool as m
        original_pool = m._POOL_PATHS.copy()
        original_hist = m._HISTORY_PATHS.copy()
        direction = "long"
        m._POOL_PATHS[direction] = os.path.join(
            tmp_dir, f"phase2_{direction}_pool.json")
        m._HISTORY_PATHS[direction] = os.path.join(
            tmp_dir, f"phase2_{direction}_history.json")

        try:
            gen = Rule_Pool_Generator(
                train_df,
                feature_infos,
                direction,
                pop_size=6,
                n_generations=2,
                seed=0,
            )

            # Replace the real engine with our recording mock
            recording_engine = _RecordingEngine()
            gen._engine = recording_engine

            gen.run()

            # The engine must have been called at least once
            assert len(recording_engine.calls) > 0, (
                "simulate_rule_batch was never called — no fitness evaluations occurred."
            )

            # Every call must use the exact Phase 2 static risk parameters
            for i, call in enumerate(recording_engine.calls):
                assert call["tp"] == PHASE2_TP, (
                    f"Call {i}: expected tp={PHASE2_TP}, got {call['tp']}"
                )
                assert call["sl"] == PHASE2_SL, (
                    f"Call {i}: expected sl={PHASE2_SL}, got {call['sl']}"
                )
                assert call["capital_pct"] == PHASE2_CAPITAL_PCT, (
                    f"Call {i}: expected capital_pct={PHASE2_CAPITAL_PCT}, "
                    f"got {call['capital_pct']}"
                )
        finally:
            m._POOL_PATHS.update(original_pool)
            m._HISTORY_PATHS.update(original_hist)


# ---------------------------------------------------------------------------
# Property 20: Rule Condition Count Bounds
# Validates: Requirements 8.6
# ---------------------------------------------------------------------------

@given(args=feature_infos_and_train_df())
@prop_settings(
    max_examples=20,
    suppress_health_check=[HealthCheck.too_slow,
                           HealthCheck.function_scoped_fixture],
    deadline=None,
)
def test_property_20_rule_condition_count_bounds(
    args: tuple[list[dict], pd.DataFrame],
) -> None:
    """
    **Property 20: Rule Condition Count Bounds**
    **Validates: Requirements 8.6**

    For any pool generated by Rule_Pool_Generator, every rule in the pool
    must have active conditions in [MIN_CONDITIONS, MAX_CONDITIONS].
    MIN_CONDITIONS=2, MAX_CONDITIONS=5.

    We verify this both via the decoded conditions list (len) and by
    re-counting active genes in the raw chromosome against the dont_care
    sentinels for the given feature_infos.
    """
    feature_infos, train_df = args

    with tempfile.TemporaryDirectory() as tmp_dir:
        # Redirect output files to a temp dir
        import gpu_fuzzy_trader.phases.phase2_rule_pool as m
        original_pool = m._POOL_PATHS.copy()
        original_hist = m._HISTORY_PATHS.copy()
        direction = "long"
        m._POOL_PATHS[direction] = os.path.join(
            tmp_dir, f"phase2_{direction}_pool.json")
        m._HISTORY_PATHS[direction] = os.path.join(
            tmp_dir, f"phase2_{direction}_history.json")

        try:
            gen = Rule_Pool_Generator(
                train_df,
                feature_infos,
                direction,
                pop_size=8,
                n_generations=3,
                seed=0,
            )
            pool = gen.run()

            dont_cares = _get_dont_cares(feature_infos)

            for i, entry in enumerate(pool):
                # --- Check via decoded conditions list ---
                n_conditions = len(entry["conditions"])
                assert MIN_CONDITIONS <= n_conditions <= MAX_CONDITIONS, (
                    f"Pool entry {i}: conditions list has {n_conditions} items, "
                    f"expected [{MIN_CONDITIONS}, {MAX_CONDITIONS}]. "
                    f"conditions={entry['conditions']}"
                )

                # --- Cross-check via raw chromosome active-gene count ---
                chromosome = np.array(entry["chromosome"], dtype=np.int32)
                active = _count_active_conditions(chromosome, dont_cares)
                assert MIN_CONDITIONS <= active <= MAX_CONDITIONS, (
                    f"Pool entry {i}: chromosome has {active} active genes, "
                    f"expected [{MIN_CONDITIONS}, {MAX_CONDITIONS}]. "
                    f"chromosome={entry['chromosome']}"
                )
        finally:
            m._POOL_PATHS.update(original_pool)
            m._HISTORY_PATHS.update(original_hist)
